config/routes.rb
Rails.application.routes.draw do

   resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  CATEGORIES = ["French", "Chinese", "Belgian", "Japanese", "Italian"] # Restaurant::CATEGORIES
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: CATEGORIES, message: "This is not a correct category!" }, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true, allow_blank: false
  validates :rating, presence: true, allow_blank: false, inclusion: { in: [0,1,2,3,4,5], allow_nil: false }, :numericality => {:only_integer => true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show

  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

end


private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end


private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<div class="container">

  <h1 class="text-center">Our restaurants</h1>


      <% @restaurants.each do |restaurant| %>
        <div class="row">
          <div class="col-sm-6 col-md-6 col-md-offset-3">
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://i.f1g.fr/media/ext/orig/www.lefigaro.fr/medias/2013/12/05/PHO9c94bd0c-5d95-11e3-9117-7d8eaf2feb0f-805x453.jpg');">
              <div class="card-category"><%= restaurant.category %></div>
                <div class="card-description">
                  <h2><%= restaurant.name %></h2>
                </div>
                <div class="card-link-forward">
                    <%= link_to 'Add review', new_restaurant_review_path(restaurant) %>
                    <%= link_to 'Edit', edit_restaurant_path(restaurant) %>
                    <%= link_to 'Delete', restaurant_path(restaurant), method: :delete %>
                </div>
            <%= link_to  "", restaurant_path(restaurant), class: "card-link" %>
            </div>
          </div>
        </div>
    <% end %>

  <h2 class="text-center"> <%= link_to 'Add restaurant', new_restaurant_path  %></h2>

</div>

app/views/restaurants/new.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h2><%= @restaurant.address %></h2>
<h2><%= @restaurant.phone_number %></h2>
<h2><%= @restaurant.category %></h2>
<% @restaurant.reviews.each do |review| %>
  <h3><%= review.content %></h3>
  <h3><%= review.rating %></h3>
<% end %>
<ul class="list-inline">
   <li><p> <%= link_to 'Add review', new_restaurant_review_path(@restaurant)  %></p></li>
   <li><p> <%= link_to 'Edit this restaurant', edit_restaurant_path(@restaurant)  %></p></li>
   <li><p> <%= link_to 'Delete this restaurant', restaurant_path(@restaurant), method: :delete  %></p></li>
</ul>

<%= link_to 'Back to all restaurant', restaurants_path  %>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
<%= f.input :content %>
<%= f.input :rating %>
<%= f.submit %>
<% end %>


<!-- <form action="restaurants/1/reviews" method="post">
  <input type="text">
</form>
 -->